CREATE TABLE parent_test_entity
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    random_string    VARCHAR(128)                            NOT NULL,
    random_date      date                                    NOT NULL,
    random_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    random_boolean   BOOLEAN,
    CONSTRAINT pk_parenttestentity PRIMARY KEY (id)
);

ALTER TABLE parent_test_entity
    ADD CONSTRAINT uc_parenttestentity_randomstring UNIQUE (random_string);

CREATE TABLE child_test_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    random_string VARCHAR(128)                            NOT NULL,
    parent        BIGINT                                  NOT NULL,
    CONSTRAINT pk_childtestentity PRIMARY KEY (id)
);

ALTER TABLE child_test_entity
    ADD CONSTRAINT uc_childtestentity_randomstring UNIQUE (random_string);

ALTER TABLE child_test_entity
    ADD CONSTRAINT FK_CHILDTESTENTITY_ON_PARENT FOREIGN KEY (parent) REFERENCES parent_test_entity (id);

INSERT INTO parent_test_entity (random_string, random_date, random_date_time, random_boolean)
VALUES ('xK9mPqL2vNwR7tYs', '2024-03-15', '2024-03-15 14:30:45', TRUE);

INSERT INTO parent_test_entity (random_string, random_date, random_date_time, random_boolean)
VALUES ('bH4jFcA8eZuW1oMn', '2024-07-22', '2024-07-22 09:15:30', FALSE);

INSERT INTO child_test_entity (random_string, parent)
VALUES ('qT6yRpD3sVxL9wKm', (SELECT id FROM parent_test_entity WHERE random_string = 'xK9mPqL2vNwR7tYs'));

INSERT INTO child_test_entity (random_string, parent)
VALUES ('nG2hJcB7fZuE4oAi', (SELECT id FROM parent_test_entity WHERE random_string = 'xK9mPqL2vNwR7tYs'));

INSERT INTO child_test_entity (random_string, parent)
VALUES ('mW5kPtC1vNxQ8rYs', (SELECT id FROM parent_test_entity WHERE random_string = 'bH4jFcA8eZuW1oMn'));

INSERT INTO child_test_entity (random_string, parent)
VALUES ('dL3jHbF9eZaU6oXn', (SELECT id FROM parent_test_entity WHERE random_string = 'bH4jFcA8eZuW1oMn'));
