CREATE TABLE all_oracle_types
(
    col_number           NUMBER,
    col_number_p         NUMBER(10),
    col_number_ps        NUMBER(10, 2),
    col_float            FLOAT,
    col_binary_float     BINARY_FLOAT,
    col_binary_double    BINARY_DOUBLE,
    col_integer          INTEGER,
    col_smallint         SMALLINT,
    col_decimal          DECIMAL(10, 2),
    col_numeric          NUMERIC(10, 2),
    col_real             REAL,
    col_double_precision DOUBLE PRECISION,
    col_char             CHAR(50),
    col_nchar            NCHAR(50),
    col_varchar2         VARCHAR2(200),
    col_nvarchar2        NVARCHAR2(200),
    col_clob             CLOB,
    col_nclob            NCLOB,
    col_long             LONG,
    col_date             DATE,
    col_timestamp        TIMESTAMP,
    col_timestamp_tz     TIMESTAMP WITH TIME ZONE,
    col_timestamp_ltz    TIMESTAMP WITH LOCAL TIME ZONE,
    col_interval_ym      INTERVAL YEAR TO MONTH,
    col_interval_ds      INTERVAL DAY TO SECOND,
    col_blob             BLOB
);

INSERT INTO all_oracle_types (col_number,
                              col_number_p,
                              col_number_ps,
                              col_float,
                              col_binary_float,
                              col_binary_double,
                              col_integer,
                              col_smallint,
                              col_decimal,
                              col_numeric,
                              col_real,
                              col_double_precision,
                              col_char,
                              col_nchar,
                              col_varchar2,
                              col_nvarchar2,
                              col_clob,
                              col_nclob,
                              col_long,
                              col_date,
                              col_timestamp,
                              col_timestamp_tz,
                              col_timestamp_ltz,
                              col_interval_ym,
                              col_interval_ds,
                              col_blob)
VALUES (123456789.987654321,
        1234567890,
        12345678.99,
        3.14159,
        3.14f,
        2.71828182845904d,
        42,
        7,
        99999.55,
        88888.44,
        1.618,
        2.302585092994046,
        'Fixed-length CHAR text with padding',
        N'NCHAR Unicode text sample',
        'Variable-length VARCHAR2 text',
        N'NVARCHAR2 Unicode text sample',
        TO_CLOB('Long CLOB content for testing purposes'),
        TO_NCLOB(N'NCLOB Unicode content for testing purposes'),
        'Legacy LONG column content',
        TO_DATE('2025-06-15 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2025-06-15 14:30:45.123456', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP_TZ('2025-06-15 14:30:45.123 -03:00', 'YYYY-MM-DD HH24:MI:SS.FF3 TZH:TZM'),
        TO_TIMESTAMP('2025-06-15 14:30:45.123456', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        INTERVAL '3-6' YEAR TO MONTH,
        INTERVAL '5 04:30:15.500' DAY TO SECOND,
        HEXTORAW('48656C6C6F20776F726C6421'));
